const data = {
  batters: {
    id0001: {
      id: 'id0001',
      id: 'id0001',
      name: 'Brendan Donovan',
      team: 'Cardinals',
      age: 25,
      pos: 'RF',
      ab: 0,
      pa: 0,
      r: 0,
      h: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      hr: 0,
      rbi: 0,
      bb: 0,
      so: 0,
      out: 0,
      con: 50,
      pow: 50,
      eye: 80,
    },
    id0002: {
      id: 'id0002',
      id: 'id0002',
      name: 'Tommy Edman',
      team: 'Cardinals',
      age: 27,
      pos: '2B',
      ab: 0,
      pa: 0,
      r: 0,
      h: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      hr: 0,
      rbi: 0,
      bb: 0,
      so: 0,
      out: 0,
      con: 50,
      pow: 50,
      eye: 70,
    },
    id0003: {
      id: 'id0003',
      name: 'Paul Goldschmidt',
      team: 'Cardinals',
      age: 35,
      pos: '1B',
      ab: 0,
      pa: 0,
      r: 0,
      h: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      hr: 0,
      rbi: 0,
      bb: 0,
      so: 0,
      out: 0,
      con: 50,
      pow: 50,
      eye: 60,
    },
    id0004: {
      id: 'id0004',
      name: 'Nolan Arenado',
      team: 'Cardinals',
      age: 31,
      pos: '3B',
      ab: 0,
      pa: 0,
      r: 0,
      h: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      hr: 0,
      rbi: 0,
      bb: 0,
      so: 0,
      out: 0,
      con: 50,
      pow: 50,
      eye: 50,
    },

    id0005: {
      id: 'id0005',
      name: 'Corey Dickerson',
      team: 'Cardinals',
      age: 33,
      pos: 'LF',
      ab: 0,
      pa: 0,
      r: 0,
      h: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      hr: 0,
      rbi: 0,
      bb: 0,
      so: 0,
      out: 0,
      con: 50,
      pow: 50,
      eye: 40,
    },
    id0006: {
      id: 'id0006',
      name: 'Albert Pujols',
      team: 'Cardinals',
      age: 42,
      pos: 'DH',
      ab: 0,
      pa: 0,
      r: 0,
      h: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      hr: 0,
      rbi: 0,
      bb: 0,
      so: 0,
      out: 0,
      con: 50,
      pow: 50,
      eye: 30,
    },
    id0007: {
      id: 'id0007',
      name: 'Lars Nootbaar',
      team: 'Cardinals',
      age: 25,
      pos: 'RF',
      ab: 0,
      pa: 0,
      r: 0,
      h: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      hr: 0,
      rbi: 0,
      bb: 0,
      so: 0,
      out: 0,
      con: 50,
      pow: 50,
      eye: 30,
    },

    id0008: {
      id: 'id0008',
      name: 'Yadier Molina',
      team: 'Cardinals',
      age: 40,
      pos: 'C',
      ab: 0,
      pa: 0,
      r: 0,
      h: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      hr: 0,
      rbi: 0,
      bb: 0,
      so: 0,
      out: 0,
      con: 50,
      pow: 50,
      eye: 30,
    },

    id0009: {
      id: 'id0009',
      name: "Tyler O'Neill",
      team: 'Cardinals',
      age: 27,
      pos: 'CF',
      ab: 0,
      pa: 0,
      r: 0,
      h: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      hr: 0,
      rbi: 0,
      bb: 0,
      so: 0,
      out: 0,
      con: 50,
      pow: 50,
      eye: 30,
    },
    id0010: {
      id: 'id0010',
      name: 'Ronald Acuna Jr',
      team: 'Braves',
      age: 24,
      pos: 'RF',
      ab: 0,
      pa: 0,
      r: 0,
      h: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      hr: 0,
      rbi: 0,
      bb: 0,
      so: 0,
      out: 0,
      con: 80,
      pow: 80,
      eye: 80,
    },
    id0011: {
      id: 'id0011',
      name: 'Dansby Swanson',
      team: 'Braves',
      age: 28,
      pos: 'SS',
      ab: 0,
      pa: 0,
      r: 0,
      h: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      hr: 0,
      rbi: 0,
      bb: 0,
      so: 0,
      out: 0,
      con: 50,
      pow: 50,
      eye: 50,
    },
    id0012: {
      id: 'id0012',
      name: 'Austin Riley',
      team: 'Braves',
      age: 25,
      pos: '3B',
      ab: 0,
      pa: 0,
      r: 0,
      h: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      hr: 0,
      rbi: 0,
      bb: 0,
      so: 0,
      out: 0,
      con: 50,
      pow: 50,
      eye: 50,
    },
    id0013: {
      id: 'id0013',
      name: 'Matt Olson',
      team: 'Braves',
      age: 28,
      pos: '1B',
      ab: 0,
      pa: 0,
      r: 0,
      h: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      hr: 0,
      rbi: 0,
      bb: 0,
      so: 0,
      out: 0,
      con: 50,
      pow: 50,
      eye: 50,
    },

    id0014: {
      id: 'id0014',
      name: 'Ozzie Albies',
      team: 'Braves',
      age: 25,
      pos: '2B',
      ab: 0,
      pa: 0,
      r: 0,
      h: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      hr: 0,
      rbi: 0,
      bb: 0,
      so: 0,
      out: 0,
      con: 50,
      pow: 50,
      eye: 50,
    },
    id0015: {
      id: 'id0015',
      name: 'Travis dArnaud',
      team: 'Braves',
      age: 33,
      pos: 'C',
      ab: 0,
      pa: 0,
      r: 0,
      h: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      hr: 0,
      rbi: 0,
      bb: 0,
      so: 0,
      out: 0,
      con: 50,
      pow: 50,
      eye: 50,
    },
    id0016: {
      id: 'id0016',
      name: 'Wilson Contreras',
      team: 'Braves',
      age: 31,
      pos: 'DH',
      ab: 0,
      pa: 0,
      r: 0,
      h: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      hr: 0,
      rbi: 0,
      bb: 0,
      so: 0,
      out: 0,
      con: 50,
      pow: 50,
      eye: 50,
    },

    id0017: {
      id: 'id0017',
      name: 'Michael Harris',
      team: 'Braves',
      age: 21,
      pos: 'CF',
      ab: 0,
      pa: 0,
      r: 0,
      h: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      hr: 0,
      rbi: 0,
      bb: 0,
      so: 0,
      out: 0,
      con: 50,
      pow: 50,
      eye: 50,
    },

    id0018: {
      id: 'id0018',
      name: 'Vaughn Grissom',
      team: 'Braves',
      age: 21,
      pos: 'LF',
      ab: 0,
      pa: 0,
      r: 0,
      h: 0,
      singles: 0,
      doubles: 0,
      triples: 0,
      hr: 0,
      rbi: 0,
      bb: 0,
      so: 0,
      out: 0,
      con: 50,
      pow: 50,
      eye: 50,
    },
  },
};

const cardinalsLineUp = [
  'id0001',
  'id0002',
  'id0003',
  'id0004',
  'id0005',
  'id0006',
  'id0007',
  'id0008',
  'id0009',
];

const bravesLineUp = [
  'id0010',
  'id0011',
  'id0012',
  'id0013',
  'id0014',
  'id0015',
  'id0016',
  'id0017',
  'id0018',
];

const player = 'id0005';

cardinalsLineUp.forEach((id) => {
  console.log(data.batters[id].name);
});
